// Product interface
export interface Product {
  id: string;
  name: string;
  price: number;
  originalPrice: number;
  image: string;
  category: string;
  subcategory?: string;
  gender?: string;
  kidGender?: string;
  rating: number;
  reviewCount?: number;
  tags?: string[];
  shortDescription?: string;
  description?: string;
  sizes?: string[];
  colors?: string[];
  material?: string;
  brand?: string;
  features?: string[];
  careInstructions?: string[];
  deliveryInfo?: string;
  returnPolicy?: string;
  fitType?: string;
  volume?: string;
  ingredients?: string[];
  benefits?: string[];
  suitableFor?: string[];
  howToUse?: string[];
}

// Sample product data - updated with numeric IDs
const products: Product[] = [
  // Men's products
  {
    id: "1",
    name: "Classic White Shirt",
    price: 1299,
    originalPrice: 1999,
    image: "/mens-white-shirt-fashion.png",
    category: "casual-wear",
    subcategory: "shirts",
    gender: "men",
    rating: 4.5,
    reviewCount: 128,
    tags: ["Best Seller", "Pure Cotton"],
    shortDescription: "Premium cotton shirt for everyday comfort",
    description:
      "This classic white shirt is made from 100% organic cotton for ultimate comfort. The breathable fabric ensures you stay fresh throughout the day, while the timeless design makes it perfect for any casual occasion. Pair it with jeans or formal pants for an effortlessly stylish look.",
  },
  {
    id: "2",
    name: "Slim Fit Jeans",
    price: 1499,
    originalPrice: 2499,
    image: "/mens-slim-fit-jeans.png",
    category: "casual-wear",
    subcategory: "pants",
    gender: "men",
    rating: 4.7,
    reviewCount: 86,
    tags: ["Trending", "Comfortable"],
    shortDescription: "Comfortable slim fit jeans with stretch fabric",
    description:
      "These slim fit jeans combine style and comfort with their premium denim fabric that includes just the right amount of stretch. The modern slim fit silhouette flatters your physique while allowing freedom of movement. Versatile enough for both casual and semi-formal occasions, these jeans will quickly become your go-to choice.",
  },
  {
    id: "3",
    name: "Casual T-Shirt",
    price: 799,
    originalPrice: 1299,
    image: "/mens-casual-tshirt-fashion.png",
    category: "casual-wear",
    subcategory: "t-shirts",
    gender: "men",
    rating: 4.4,
    reviewCount: 89,
    tags: ["Casual", "Comfortable"],
    shortDescription: "Comfortable casual t-shirt for everyday wear",
    description:
      "This casual t-shirt is perfect for your everyday wardrobe. Made from soft, breathable fabric that keeps you comfortable all day long. The relaxed fit and durable construction ensure it will be a staple in your closet for seasons to come. Available in multiple colors to match any style.",
  },
  {
    id: "4",
    name: "Formal Shirt",
    price: 1599,
    originalPrice: 2599,
    image: "/mens-formal-shirt-fashion.png",
    category: "formal-wear",
    subcategory: "shirts",
    gender: "men",
    rating: 4.6,
    reviewCount: 112,
    tags: ["Formal", "Business"],
    shortDescription: "Crisp formal shirt for professional settings",
    description:
      "Make a professional impression with this crisp formal shirt. Tailored for a perfect fit with wrinkle-resistant fabric that keeps you looking sharp throughout the day. The classic design features a standard collar and button cuffs, making it versatile for various business and formal occasions.",
  },
  {
    id: "5",
    name: "Formal Pants",
    price: 1899,
    originalPrice: 2999,
    image: "/mens-formal-pants-fashion.png",
    category: "formal-wear",
    subcategory: "pants",
    gender: "men",
    rating: 4.3,
    reviewCount: 68,
    tags: ["Formal", "Office Wear"],
    shortDescription: "Classic formal pants for professional attire",
    description:
      "Complete your professional wardrobe with these classic formal pants. The tailored fit and premium fabric create a polished look suitable for business meetings and formal events. The comfortable waistband and durable construction ensure all-day comfort and long-lasting wear.",
  },
  {
    id: "6",
    name: "Oversized Shirt",
    price: 1399,
    originalPrice: 2199,
    image: "/mens-oversized-shirt-fashion.png",
    category: "oversized-fit",
    subcategory: "shirts",
    gender: "men",
    rating: 4.7,
    reviewCount: 94,
    tags: ["Trending", "Casual"],
    shortDescription: "Stylish oversized shirt for a relaxed look",
    description:
      "Embrace the oversized trend with this stylish shirt. The relaxed fit provides ultimate comfort while maintaining a fashionable appearance. Perfect for casual outings or lounging at home, this versatile piece can be styled in numerous ways to create different looks.",
  },
  {
    id: "7",
    name: "Oversized Pants",
    price: 1699,
    originalPrice: 2599,
    image: "/mens-baggy-pants-fashion.png",
    category: "oversized-fit",
    subcategory: "pants",
    gender: "men",
    rating: 4.4,
    reviewCount: 72,
    tags: ["Trending", "Comfortable"],
    shortDescription: "Comfortable oversized pants for a relaxed fit",
    description:
      "These oversized pants offer both style and comfort with their relaxed fit and premium fabric. The loose silhouette provides freedom of movement while maintaining a fashionable appearance. Perfect for casual outings or lounging at home, these pants will quickly become a staple in your wardrobe.",
  },
  {
    id: "8",
    name: "Polo T-Shirt",
    price: 999,
    originalPrice: 1599,
    image: "/placeholder.svg?key=kww7e",
    category: "oversized-fit",
    subcategory: "polo-t-shirts",
    gender: "men",
    rating: 4.6,
    reviewCount: 88,
    tags: ["Classic", "Casual"],
    shortDescription: "Classic polo t-shirt for a smart casual look",
    description:
      "This classic polo t-shirt combines comfort and style for a smart casual look. The premium cotton fabric ensures breathability and softness, while the traditional design with a collar and button placket adds a touch of sophistication. Perfect for casual Fridays at work or weekend outings.",
  },
  {
    id: "9",
    name: "Round Neck T-Shirt",
    price: 899,
    originalPrice: 1399,
    image: "/men-round-neck-t-shirt.png",
    category: "oversized-fit",
    subcategory: "round-neck-t-shirts",
    gender: "men",
    rating: 4.2,
    reviewCount: 64,
    tags: ["Basic", "Everyday"],
    shortDescription: "Comfortable round neck t-shirt for everyday wear",
    description:
      "This comfortable round neck t-shirt is perfect for everyday wear. Made from soft, breathable cotton, it keeps you comfortable throughout the day. The simple design makes it versatile enough to pair with any bottom, from jeans to shorts, for a casual, effortless look.",
  },
  {
    id: "10",
    name: "Oversized Hoodie",
    price: 1899,
    originalPrice: 2999,
    image: "/men-oversized-hoodie.png",
    category: "oversized-fit",
    subcategory: "hoodies",
    gender: "men",
    rating: 4.8,
    reviewCount: 156,
    tags: ["Winter Collection", "Warm"],
    shortDescription: "Warm and comfortable hoodie for cold days",
    description:
      "Stay warm and stylish with this oversized hoodie. The soft fleece lining provides excellent insulation, while the adjustable hood offers additional protection from the elements. Perfect for lazy weekends or casual outings, this versatile hoodie is a must-have for your winter wardrobe.",
  },
  {
    id: "11",
    name: "Vest",
    price: 499,
    originalPrice: 799,
    image: "/men-white-vest-innerwear.png",
    category: "innerwear",
    subcategory: "vests",
    gender: "men",
    rating: 4.1,
    reviewCount: 52,
    tags: ["Innerwear", "Basic"],
    shortDescription: "Comfortable cotton vest for everyday wear",
    description:
      "This comfortable cotton vest is designed for everyday wear. The soft, breathable fabric keeps you cool and comfortable throughout the day. The sleeveless design makes it perfect for wearing under shirts or as a standalone piece during hot weather.",
  },
  {
    id: "12",
    name: "Gym Vest",
    price: 599,
    originalPrice: 999,
    image: "/men-gym-tank-top.png",
    category: "innerwear",
    subcategory: "gym-vests",
    gender: "men",
    rating: 4.6,
    reviewCount: 78,
    tags: ["Gym Wear", "Active"],
    shortDescription: "Moisture-wicking gym vest for workouts",
    description:
      "Enhance your workout experience with this moisture-wicking gym vest. The lightweight, breathable fabric keeps you cool and dry during intense exercise sessions. The sleeveless design provides unrestricted movement, making it perfect for any type of workout, from weightlifting to cardio.",
  },
  {
    id: "13",
    name: "Briefs",
    price: 399,
    originalPrice: 699,
    image: "/men-briefs-fashion.png",
    category: "innerwear",
    subcategory: "briefs",
    gender: "men",
    rating: 4.3,
    reviewCount: 62,
    tags: ["Innerwear", "Pack of 3"],
    shortDescription: "Comfortable cotton briefs for everyday wear",
    description:
      "These comfortable cotton briefs are designed for everyday wear. The soft, breathable fabric ensures all-day comfort, while the elastic waistband provides a secure fit. Each pack contains three briefs in different colors, offering variety and value.",
  },

  // Women's products
  {
    id: "14",
    name: "Formal Shirt",
    price: 1499,
    originalPrice: 2499,
    image: "/formal-shirt-business-woman.png",
    category: "formal-wear",
    subcategory: "shirts",
    gender: "women",
    rating: 4.6,
    reviewCount: 94,
    tags: ["Formal", "Office Wear"],
    shortDescription: "Elegant formal shirt for professional women",
    description:
      "This elegant formal shirt is designed for the modern professional woman. The tailored fit and premium fabric create a polished look that transitions seamlessly from day to evening. The wrinkle-resistant material ensures you look crisp and put-together throughout your busy day. Pair with formal pants or a skirt for a complete business look. Features include a classic collar, button-down front, and adjustable cuffs for versatile styling options.",
  },
  {
    id: "15",
    name: "Formal Pants",
    price: 1799,
    originalPrice: 2899,
    image: "/formal-pants-business-fashion.png",
    category: "formal-wear",
    subcategory: "pants",
    gender: "women",
    rating: 4.5,
    reviewCount: 78,
    tags: ["Formal", "Office Wear"],
    shortDescription: "Tailored formal pants for a professional look",
    description:
      "These tailored formal pants are a must-have for your professional wardrobe. Made from premium stretch fabric that offers both comfort and structure, they maintain their shape throughout the day while allowing freedom of movement. The classic straight-leg silhouette is flattering and timeless, making these pants a versatile addition to your work attire. Complete with practical pockets and a comfortable waistband, they're designed for all-day wear.",
  },
  {
    id: "16",
    name: "Casual Shirt",
    price: 1299,
    originalPrice: 1999,
    image: "/women-casual-shirt-fashion.png",
    category: "casual-wear",
    subcategory: "shirts",
    gender: "women",
    rating: 4.5,
    reviewCount: 78,
    tags: ["Casual", "Weekend"],
    shortDescription: "Comfortable casual shirt for relaxed style",
    description:
      "This comfortable casual shirt is perfect for weekend outings or relaxed office environments. Made from soft, breathable fabric, it offers both style and comfort. The versatile design can be dressed up with accessories or kept simple for a more laid-back look. Features include a relaxed fit, button-down front, and a slightly longer back hem for a modern silhouette. Available in multiple colors, this shirt will quickly become a staple in your casual wardrobe.",
  },
  {
    id: "17",
    name: "Casual Pants",
    price: 1399,
    originalPrice: 2199,
    image: "/women-casual-pants.png",
    category: "casual-wear",
    subcategory: "pants",
    gender: "women",
    rating: 4.4,
    reviewCount: 65,
    tags: ["Casual", "Comfortable"],
    shortDescription: "Relaxed fit casual pants for everyday wear",
    description:
      "These relaxed fit casual pants combine style and comfort for your everyday wardrobe. The premium cotton blend fabric provides breathability and softness, while the thoughtful design includes practical pockets and an adjustable waistband. Perfect for casual outings, weekend errands, or relaxed work environments, these pants offer versatility and all-day comfort. The tapered leg creates a flattering silhouette that pairs well with both casual and semi-formal tops.",
  },
  {
    id: "18",
    name: "Casual T-Shirt",
    price: 899,
    originalPrice: 1399,
    image: "/casual-tshirt-fashion.png",
    category: "casual-wear",
    subcategory: "t-shirts",
    gender: "women",
    rating: 4.3,
    reviewCount: 92,
    tags: ["Casual", "Everyday"],
    shortDescription: "Soft cotton t-shirt for everyday comfort",
    description:
      "This soft cotton t-shirt is a versatile essential for your casual wardrobe. Made from premium combed cotton, it offers exceptional softness and durability for everyday wear. The classic fit is neither too tight nor too loose, providing a flattering silhouette that works with any bottom. The breathable fabric keeps you comfortable throughout the day, while the reinforced stitching ensures this tee will remain a staple in your wardrobe for seasons to come.",
  },
  {
    id: "19",
    name: "Oversized Shirt",
    price: 1399,
    originalPrice: 2199,
    image: "/oversized-shirt-fashion.png",
    category: "oversized-fit",
    subcategory: "shirts",
    gender: "women",
    rating: 4.7,
    reviewCount: 103,
    tags: ["Trending", "Casual"],
    shortDescription: "Stylish oversized shirt for a relaxed look",
    description:
      "Embrace the oversized trend with this stylish shirt. The relaxed fit provides ultimate comfort while maintaining a fashionable appearance. Perfect for casual outings or lounging at home, this versatile piece can be styled in numerous ways. Wear it loose over leggings, tied at the waist with jeans, or layered over a tank top. The high-quality fabric ensures durability while the thoughtful details like dropped shoulders and a longer back hem add to its contemporary appeal.",
  },
  {
    id: "20",
    name: "Oversized Pants",
    price: 1599,
    originalPrice: 2599,
    image: "/oversized-pants-fashion.png",
    category: "oversized-fit",
    subcategory: "pants",
    gender: "women",
    rating: 4.5,
    reviewCount: 87,
    tags: ["Trending", "Comfortable"],
    shortDescription: "Comfortable oversized pants for a relaxed fit",
    description:
      "These oversized pants offer both style and comfort with their relaxed fit and premium fabric. The loose silhouette provides freedom of movement while maintaining a fashionable appearance. Perfect for casual outings or lounging at home, these pants will quickly become a staple in your wardrobe. Features include an elastic waistband with drawstring for adjustable comfort, deep pockets, and ankle cuffs that create a modern silhouette. Pair with a fitted top to balance the oversized look.",
  },
  {
    id: "21",
    name: "Polo T-Shirt",
    price: 999,
    originalPrice: 1599,
    image: "/women-polo-fashion.png",
    category: "casual-wear",
    subcategory: "polo-t-shirts",
    gender: "women",
    rating: 4.4,
    reviewCount: 76,
    tags: ["Classic", "Casual"],
    shortDescription: "Classic polo t-shirt for a smart casual look",
    description:
      "This classic polo t-shirt combines comfort and style for a smart casual look. The premium cotton piqué fabric ensures breathability and softness, while the traditional design with a collar and button placket adds a touch of sophistication. Perfect for casual Fridays at work or weekend outings, this versatile piece can be dressed up or down depending on the occasion. The slightly tailored fit flatters your silhouette without being too tight, making it comfortable for all-day wear.",
  },
  {
    id: "22",
    name: "Round Neck T-Shirt",
    price: 899,
    originalPrice: 1399,
    image: "/women-round-neck-t-shirt.png",
    category: "casual-wear",
    subcategory: "round-neck-t-shirts",
    gender: "women",
    rating: 4.2,
    reviewCount: 68,
    tags: ["Basic", "Everyday"],
    shortDescription: "Comfortable round neck t-shirt for everyday wear",
    description:
      "This comfortable round neck t-shirt is perfect for everyday wear. Made from soft, breathable cotton, it keeps you comfortable throughout the day. The simple design makes it versatile enough to pair with any bottom, from jeans to skirts, for a casual, effortless look. The medium-weight fabric provides the perfect balance between structure and drape, while the reinforced seams ensure durability. Available in multiple colors, this t-shirt is a wardrobe essential that you'll reach for again and again.",
  },
  {
    id: "23",
    name: "Oversized Hoodie",
    price: 1799,
    originalPrice: 2899,
    image: "/oversized-hoodie-fashion.png",
    category: "oversized-fit",
    subcategory: "hoodies",
    gender: "women",
    rating: 4.8,
    reviewCount: 112,
    tags: ["Cozy", "Lounge Wear"],
    shortDescription: "Cozy oversized hoodie for ultimate comfort",
    description:
      "Wrap yourself in comfort with this oversized hoodie. The soft fleece lining provides warmth while the roomy design ensures unrestricted movement. Perfect for lounging at home or casual outings when paired with leggings or jeans. Features include a spacious hood, kangaroo pocket, and ribbed cuffs and hem for a secure fit. The premium cotton-polyester blend offers the perfect balance of softness and durability, making this hoodie a long-lasting addition to your casual wardrobe.",
  },
  {
    id: "24",
    name: "Bra",
    price: 799,
    originalPrice: 1299,
    image: "/lingerie-fashion-photography.png",
    category: "lingerie-innerwear",
    subcategory: "bra",
    gender: "women",
    rating: 4.6,
    reviewCount: 124,
    tags: ["Lingerie", "Comfortable"],
    shortDescription: "Comfortable and supportive everyday bra",
    description:
      "This comfortable and supportive everyday bra is designed to provide all-day comfort without compromising on style. The soft, breathable fabric and seamless construction minimize irritation, while the adjustable straps and multiple hook-and-eye closures ensure a perfect fit. The lightly padded cups provide natural shaping and support, making this bra suitable for a variety of outfits. Available in multiple colors, this versatile bra is a must-have for your lingerie collection.",
  },
  {
    id: "25",
    name: "Fashion Top",
    price: 1199,
    originalPrice: 1899,
    image: "/women-fashion-top.png",
    category: "western-wear",
    subcategory: "tops",
    gender: "women",
    rating: 4.5,
    reviewCount: 89,
    tags: ["Trendy", "Casual"],
    shortDescription: "Stylish fashion top for a contemporary look",
    description:
      "This stylish fashion top adds a contemporary touch to your casual wardrobe. The modern design features a flattering silhouette that works well with jeans, skirts, or formal pants. Made from high-quality fabric that drapes beautifully, this top offers both comfort and style for various occasions. The thoughtful details like the unique neckline and subtle pattern elevate this piece beyond a basic top, making it perfect for both everyday wear and special outings when paired with the right accessories.",
  },
  {
    id: "26",
    name: "Skinny Jeans",
    price: 1699,
    originalPrice: 2699,
    image: "/women-skinny-jeans-fashion.png",
    category: "western-wear",
    subcategory: "jeans-jeggings",
    gender: "women",
    rating: 4.7,
    reviewCount: 106,
    tags: ["Denim", "Fitted"],
    shortDescription: "Classic skinny jeans with comfortable stretch",
    description:
      "These classic skinny jeans combine style and comfort with their premium denim fabric that includes just the right amount of stretch. The modern skinny fit silhouette flatters your figure while allowing freedom of movement. The mid-rise waist provides comfortable coverage and pairs well with both cropped and tucked-in tops. Featuring traditional five-pocket styling and durable construction, these versatile jeans will quickly become your go-to choice for both casual and semi-formal occasions.",
  },
  {
    id: "27",
    name: "Pleated Skirt",
    price: 1299,
    originalPrice: 1999,
    image: "/pleated-skirt-fashion.png",
    category: "western-wear",
    subcategory: "skirts-shorts",
    gender: "women",
    rating: 4.4,
    reviewCount: 72,
    tags: ["Elegant", "Versatile"],
    shortDescription: "Elegant pleated skirt for versatile styling",
    description:
      "This elegant pleated skirt offers versatile styling options for both casual and formal occasions. The flowing pleats create movement and dimension, while the comfortable waistband ensures a secure fit throughout the day. Made from high-quality fabric with excellent drape, this skirt maintains its shape and pleats even after multiple wears. The midi length is universally flattering and appropriate for various settings, from the office to weekend outings. Pair with a blouse for a formal look or a casual t-shirt for a more relaxed style.",
  },
  {
    id: "28",
    name: "Casual Shoes",
    price: 1499,
    originalPrice: 2499,
    image: "/women-casual-shoes-fashion.png",
    category: "footwear",
    subcategory: "flats",
    gender: "women",
    rating: 4.5,
    reviewCount: 83,
    tags: ["Comfortable", "Everyday"],
    shortDescription: "Comfortable casual shoes for everyday wear",
    description:
      "These comfortable casual shoes are designed for everyday wear, providing both style and support for your feet. The cushioned insole and flexible outsole ensure all-day comfort, while the sleek design pairs well with various outfits, from jeans to dresses. The premium materials offer durability and breathability, keeping your feet comfortable in different weather conditions. The easy slip-on style makes these shoes a convenient choice for busy days, while the subtle detailing adds a touch of elegance to a practical footwear option.",
  },
  {
    id: "29",
    name: "Heeled Sandals",
    price: 1899,
    originalPrice: 2999,
    image: "/heeled-sandals-fashion.png",
    category: "footwear",
    subcategory: "heels",
    gender: "women",
    rating: 4.6,
    reviewCount: 94,
    tags: ["Elegant", "Occasion Wear"],
    shortDescription: "Elegant heeled sandals for special occasions",
    description:
      "These elegant heeled sandals are perfect for special occasions, adding a touch of sophistication to your outfit. The moderate heel height offers a good balance between style and comfort, allowing you to wear them for extended periods. The cushioned footbed provides support, while the adjustable ankle strap ensures a secure fit. Made from high-quality materials with attention to detail, these versatile sandals complement both formal dresses and more casual evening attire, making them a valuable addition to your footwear collection.",
  },
  {
    id: "30",
    name: "Stylish Handbag",
    price: 2499,
    originalPrice: 3999,
    image: "/stylish-handbag-shoot.png",
    category: "accessories",
    subcategory: "bags",
    gender: "women",
    rating: 4.8,
    reviewCount: 118,
    tags: ["Trendy", "Spacious"],
    shortDescription: "Stylish and spacious handbag for everyday use",
    description:
      "This stylish and spacious handbag is designed for the modern woman who needs both functionality and fashion in her accessories. The thoughtfully designed interior includes multiple compartments and pockets to organize your essentials, while the sturdy construction ensures durability for everyday use. The premium materials and quality hardware add a touch of luxury, while the versatile design complements various outfits and occasions. Complete with both top handles and a detachable shoulder strap, this handbag offers multiple carrying options for your convenience.",
  },

  // Kids' products with detailed information
  {
    id: "kids-cotton-tshirt",
    name: "Kids Cotton T-Shirt",
    price: 499,
    originalPrice: 699,
    image: "/boys-cotton-t-shirt-fashion.png",
    category: "clothing",
    subcategory: "t-shirts",
    gender: "kids",
    kidGender: "boy",
    rating: 4.7,
    reviewCount: 86,
    tags: ["Bestseller", "Organic", "Comfortable"],
    shortDescription: "Soft and comfortable cotton t-shirt for active kids",
    description:
      "This kids' cotton t-shirt is made from 100% organic cotton that's gentle on your child's skin. The breathable fabric keeps them comfortable during play and school activities. The durable construction with reinforced stitching ensures it withstands multiple washes and active wear. Available in vibrant colors with playful prints that kids love.",
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-12Y"],
    colors: ["Blue", "Red", "Yellow", "Green", "White"],
    material: "100% Organic Cotton",
    brand: "KidComfort",
    features: [
      "Breathable fabric for all-day comfort",
      "Reinforced stitching for durability",
      "Tag-free design to prevent skin irritation",
      "Pre-shrunk fabric",
      "Machine washable",
    ],
    careInstructions: [
      "Machine wash cold with like colors",
      "Tumble dry low",
      "Do not bleach",
      "Do not iron print",
    ],
    deliveryInfo:
      "Free delivery on orders above ₹999. Standard delivery in 3-5 business days.",
    returnPolicy: "Easy 30-day returns if you're not completely satisfied.",
    fitType: "Regular fit",
  },
  {
    id: "kids-denim-jeans",
    name: "Kids Denim Jeans",
    price: 799,
    originalPrice: 999,
    image: "/boys-jeans-fashion.png",
    category: "clothing",
    subcategory: "bottoms",
    gender: "kids",
    kidGender: "boy",
    rating: 4.5,
    reviewCount: 72,
    tags: ["Durable", "Adjustable", "Comfortable"],
    shortDescription:
      "Durable denim jeans with adjustable waistband for growing kids",
    description:
      "These durable denim jeans are designed for active kids who need clothing that can keep up with their adventures. The adjustable waistband ensures a perfect fit as they grow, while the reinforced knees and pockets make these jeans perfect for everyday wear. Made from soft denim with just the right amount of stretch for comfort and mobility.",
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-12Y"],
    colors: ["Blue", "Light Blue", "Black"],
    material: "98% Cotton, 2% Elastane",
    brand: "KidComfort",
    features: [
      "Adjustable waistband for growing kids",
      "Reinforced knees for durability",
      "Multiple pockets for small treasures",
      "Soft inner lining for comfort",
      "Easy pull-on style for younger kids",
    ],
    careInstructions: [
      "Machine wash cold inside out",
      "Tumble dry medium",
      "Do not bleach",
      "Warm iron if needed",
    ],
    deliveryInfo:
      "Free delivery on orders above ₹999. Standard delivery in 3-5 business days.",
    returnPolicy: "Easy 30-day returns if you're not completely satisfied.",
    fitType: "Regular fit",
  },
  {
    id: "kids-cotton-vest",
    name: "Kids Cotton Vest",
    price: 349,
    originalPrice: 499,
    image: "/boys-cotton-vest-innerwear.png",
    category: "innerwear",
    subcategory: "vests",
    gender: "kids",
    kidGender: "boy",
    rating: 4.8,
    reviewCount: 64,
    tags: ["Innerwear", "Soft", "Pack of 3"],
    shortDescription: "Ultra-soft cotton vests for everyday comfort",
    description:
      "These ultra-soft cotton vests are designed for maximum comfort for your child. Made with hypoallergenic cotton that's gentle on sensitive skin, these vests are perfect as undershirts or for warm weather. The reinforced shoulder seams ensure durability, while the tag-free design prevents skin irritation. Each pack contains three vests in different colors.",
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-12Y"],
    colors: ["White", "Grey", "Blue"],
    material: "100% Combed Cotton",
    brand: "KidComfort",
    features: [
      "Super soft combed cotton",
      "Hypoallergenic fabric",
      "Reinforced shoulder seams",
      "Tag-free design",
      "Maintains shape after washing",
    ],
    careInstructions: [
      "Machine wash warm",
      "Tumble dry low",
      "Do not bleach",
      "Do not iron",
    ],
    deliveryInfo:
      "Free delivery on orders above ₹999. Standard delivery in 3-5 business days.",
    returnPolicy: "Easy 30-day returns if you're not completely satisfied.",
    fitType: "Regular fit",
  },
  {
    id: "kids-sports-shoes",
    name: "Kids Sports Shoes",
    price: 999,
    originalPrice: 1299,
    image: "/boys-sports-shoes-fashion.png",
    category: "footwear",
    subcategory: "sports-shoes",
    gender: "kids",
    kidGender: "boy",
    rating: 4.6,
    reviewCount: 78,
    tags: ["Active", "Comfortable", "Durable"],
    shortDescription: "Lightweight and durable sports shoes for active kids",
    description:
      "These lightweight and durable sports shoes are designed for active kids who love to run, jump, and play. The cushioned insoles provide comfort, while the non-slip soles ensure safety during play. The breathable materials keep feet cool and comfortable all day, and the easy-to-use closure makes them perfect for kids of all ages.",
    sizes: [
      "UK 8C",
      "UK 9C",
      "UK 10C",
      "UK 11C",
      "UK 12C",
      "UK 13C",
      "UK 1",
      "UK 2",
      "UK 3",
    ],
    colors: ["Blue/Red", "Black/Green", "Grey/Orange"],
    material: "Synthetic Mesh, Rubber Sole",
    brand: "KidStep",
    features: [
      "Lightweight and flexible design",
      "Cushioned insoles for comfort",
      "Non-slip rubber outsoles",
      "Easy velcro closure for younger kids",
      "Reflective elements for visibility",
      "Breathable mesh upper",
    ],
    careInstructions: [
      "Wipe clean with damp cloth",
      "Air dry away from direct heat",
      "Do not machine wash",
      "Remove insoles to dry separately if wet",
    ],
    deliveryInfo:
      "Free delivery on orders above ₹999. Standard delivery in 3-5 business days.",
    returnPolicy: "Easy 30-day returns if you're not completely satisfied.",
    fitType: "Regular fit",
  },
  {
    id: "kids-festive-kurta",
    name: "Kids Festive Kurta Set",
    price: 1299,
    originalPrice: 1699,
    image: '/boys-kurta-set-    "Kids Festive Kurta Set',
    price: 1299,
    originalPrice: 1699,
    image: "/boys-kurta-set-fashion.png",
    category: "ethnic-wear",
    subcategory: "kurta-sets",
    gender: "kids",
    kidGender: "boy",
    rating: 4.9,
    reviewCount: 56,
    tags: ["Festive", "Ethnic", "Occasion Wear"],
    shortDescription: "Elegant festive kurta set for special occasions",
    description:
      "This elegant festive kurta set is perfect for special occasions and celebrations. Made with premium cotton fabric with intricate embroidery details, it offers both style and comfort for your child. The set includes a kurta and matching bottom wear for a complete traditional look. The comfortable fit ensures your child can enjoy festivities without any discomfort.",
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-12Y"],
    colors: ["Blue", "Maroon", "Gold"],
    material: "Cotton Blend with Embroidery",
    brand: "LittleFestive",
    features: [
      "Premium cotton blend fabric",
      "Intricate embroidery details",
      "Comfortable fit for long wear",
      "Includes matching bottom wear",
      "Button-down front",
    ],
    careInstructions: [
      "Dry clean recommended",
      "Gentle hand wash in cold water if needed",
      "Do not bleach",
      "Iron on medium heat",
    ],
    deliveryInfo:
      "Free delivery on orders above ₹999. Standard delivery in 3-5 business days.",
    returnPolicy: "Easy 30-day returns if you're not completely satisfied.",
    fitType: "Regular fit",
  },
  {
    id: "girls-pajama-set",
    name: "Girls Printed Pajama Set",
    price: 799,
    originalPrice: 999,
    image: "/girls-pajama-fashion.png",
    category: "nightwear",
    subcategory: "pajama-sets",
    gender: "kids",
    kidGender: "girl",
    rating: 4.8,
    reviewCount: 62,
    tags: ["Nightwear", "Comfortable", "Cute Prints"],
    shortDescription: "Soft and cozy printed pajama set for girls",
    description:
      "This soft and cozy printed pajama set is designed for ultimate comfort during sleep and lounging. Made with breathable cotton fabric that's gentle on your child's skin, these pajamas feature cute prints that kids love. The set includes a long-sleeve top and matching bottoms with an elastic waistband for a comfortable fit. Perfect for bedtime or lazy weekend mornings.",
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-12Y"],
    colors: ["Pink", "Purple", "Blue"],
    material: "100% Cotton",
    brand: "DreamyKids",
    features: [
      "Super soft cotton fabric",
      "Cute all-over prints",
      "Elastic waistband for comfort",
      "Long-sleeve top with matching bottoms",
      "Tag-free design for sensitive skin",
    ],
    careInstructions: [
      "Machine wash cold",
      "Tumble dry low",
      "Do not bleach",
      "Iron on low heat if needed",
    ],
    deliveryInfo:
      "Free delivery on orders above ₹999. Standard delivery in 3-5 business days.",
    returnPolicy: "Easy 30-day returns if you're not completely satisfied.",
    fitType: "Relaxed fit",
  },
  {
    id: "girls-festive-lehenga",
    name: "Girls Festive Lehenga",
    price: 1499,
    originalPrice: 1999,
    image: "/girls-lehenga-fashion.png",
    category: "ethnic-wear",
    subcategory: "lehenga-sets",
    gender: "kids",
    kidGender: "girl",
    rating: 4.9,
    reviewCount: 48,
    tags: ["Festive", "Ethnic", "Occasion Wear"],
    shortDescription: "Beautiful festive lehenga for special occasions",
    description:
      "This beautiful festive lehenga is designed for special occasions and celebrations. The intricate embroidery and sequin work add a touch of elegance, while the comfortable fit ensures your child can enjoy festivities without any discomfort. The set includes a lehenga skirt, choli top, and dupatta for a complete traditional look. Made with premium fabric that's both beautiful and comfortable.",
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-12Y"],
    colors: ["Pink", "Blue", "Green", "Red"],
    material: "Art Silk with Embroidery",
    brand: "LittleFestive",
    features: [
      "Premium art silk fabric",
      "Intricate embroidery and sequin work",
      "Flared lehenga for twirl effect",
      "Includes matching choli top and dupatta",
      "Elastic waistband for comfort",
    ],
    careInstructions: [
      "Dry clean only",
      "Store in a cool, dry place",
      "Do not bleach",
      "Iron on low heat",
    ],
    deliveryInfo:
      "Free delivery on orders above ₹999. Standard delivery in 3-5 business days.",
    returnPolicy: "Easy 30-day returns if you're not completely satisfied.",
    fitType: "Regular fit",
  },
  {
    id: "kids-winter-jacket",
    name: "Kids Winter Jacket",
    price: 1499,
    originalPrice: 1999,
    image: "/kids-winter-jacket.png",
    category: "clothing",
    subcategory: "outerwear",
    gender: "kids",
    kidGender: "boy",
    rating: 4.8,
    reviewCount: 58,
    tags: ["Winter", "Warm", "Waterproof"],
    shortDescription: "Warm and waterproof winter jacket for kids",
    description:
      "Keep your child warm and dry with this high-quality winter jacket. Featuring a waterproof outer shell and cozy inner lining, this jacket is perfect for cold weather. The adjustable hood and cuffs help keep the cold out, while the multiple pockets provide space for small essentials. The reflective details add visibility during darker winter days.",
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-12Y"],
    colors: ["Blue", "Red", "Black"],
    material: "Outer: 100% Polyester, Inner: Fleece Lining",
    brand: "KidComfort",
    features: [
      "Waterproof outer shell",
      "Warm fleece lining",
      "Adjustable hood and cuffs",
      "Multiple pockets",
      "Reflective details for visibility",
    ],
    careInstructions: [
      "Machine wash cold",
      "Tumble dry low",
      "Do not bleach",
      "Do not iron",
    ],
    deliveryInfo:
      "Free delivery on orders above ₹999. Standard delivery in 3-5 business days.",
    returnPolicy: "Easy 30-day returns if you're not completely satisfied.",
    fitType: "Regular fit",
  },
  {
    id: "girls-summer-dress",
    name: "Girls Summer Dress",
    price: 899,
    originalPrice: 1299,
    image: "/placeholder-hntqn.png",
    category: "clothing",
    subcategory: "dresses",
    gender: "kids",
    kidGender: "girl",
    rating: 4.7,
    reviewCount: 64,
    tags: ["Summer", "Casual", "Cotton"],
    shortDescription: "Light and comfortable summer dress for girls",
    description:
      "This light and comfortable summer dress is perfect for warm days. Made from 100% cotton, it keeps your child cool and comfortable all day long. The playful print and twirl-friendly design make it a favorite among young girls. The easy-care fabric is machine washable and maintains its shape and color even after multiple washes.",
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-12Y"],
    colors: ["Pink", "Blue", "Yellow"],
    material: "100% Cotton",
    brand: "KidComfort",
    features: [
      "Lightweight and breathable fabric",
      "Playful print design",
      "Twirl-friendly full skirt",
      "Easy pull-on style",
      "Machine washable",
    ],
    careInstructions: [
      "Machine wash cold",
      "Tumble dry low",
      "Do not bleach",
      "Iron on low if needed",
    ],
    deliveryInfo:
      "Free delivery on orders above ₹999. Standard delivery in 3-5 business days.",
    returnPolicy: "Easy 30-day returns if you're not completely satisfied.",
    fitType: "Regular fit",
  },
  {
    id: "kids-school-backpack",
    name: "Kids School Backpack",
    price: 799,
    originalPrice: 1199,
    image: "/colorful-kids-backpack.png",
    category: "accessories",
    subcategory: "bags",
    gender: "kids",
    kidGender: "boy",
    rating: 4.6,
    reviewCount: 92,
    tags: ["School", "Durable", "Spacious"],
    shortDescription: "Durable and spacious school backpack for kids",
    description:
      "This durable and spacious school backpack is designed to carry all your child's school essentials. The padded shoulder straps and back panel ensure comfort even when the bag is fully loaded. Multiple compartments help organize books, stationery, and lunch boxes, while the water-resistant material keeps everything dry during light rain. The fun design and bright colors make this backpack a hit among school children.",
    colors: ["Blue", "Red", "Green", "Purple"],
    material: "Durable Polyester, Water-resistant",
    brand: "KidGear",
    features: [
      "Padded shoulder straps and back panel",
      "Multiple compartments for organization",
      "Water-resistant material",
      "Reinforced bottom for durability",
      "Name tag inside",
    ],
    careInstructions: [
      "Spot clean with damp cloth",
      "Air dry",
      "Do not machine wash",
      "Do not bleach",
    ],
    deliveryInfo:
      "Free delivery on orders above ₹999. Standard delivery in 3-5 business days.",
    returnPolicy: "Easy 30-day returns if you're not completely satisfied.",
  },

  // Beauty products
  {
    id: "gentle-facial-cleanser",
    name: "Gentle Facial Cleanser",
    price: 599,
    originalPrice: 999,
    image: "/facial-cleanser-product.png",
    category: "skincare",
    subcategory: "cleanser",
    gender: "beauty",
    rating: 4.7,
    reviewCount: 186,
    tags: ["Gentle", "For All Skin Types"],
    shortDescription: "Gentle yet effective cleanser for all skin types",
    description:
      "This gentle facial cleanser effectively removes impurities without stripping your skin's natural moisture. Formulated with soothing botanical extracts and mild surfactants, it cleanses deeply while maintaining your skin's natural balance. Perfect for daily use, this cleanser prepares your skin for the rest of your skincare routine while leaving it feeling fresh and comfortable.",
    volume: "200ml",
    brand: "PureGlow",
    ingredients: [
      "Purified Water",
      "Glycerin",
      "Sodium Cocoyl Isethionate",
      "Aloe Vera Extract",
      "Chamomile Extract",
      "Green Tea Extract",
      "Vitamin E",
      "Citric Acid",
      "Natural Fragrance",
    ],
    benefits: [
      "Removes dirt, oil, and makeup without drying the skin",
      "Maintains skin's natural pH balance",
      "Soothes and calms sensitive skin",
      "Helps prevent breakouts",
      "Prepares skin for better absorption of other skincare products",
    ],
    suitableFor: [
      "All skin types",
      "Sensitive skin",
      "Acne-prone skin",
      "Dry skin",
      "Combination skin",
    ],
    howToUse: [
      "Wet face with lukewarm water",
      "Apply a small amount to fingertips and work into a lather",
      "Massage gently onto face using circular motions",
      "Rinse thoroughly with water",
      "Use morning and evening for best results",
    ],
    deliveryInfo:
      "Free delivery on orders above ₹999. Standard delivery in 3-5 business days.",
    returnPolicy:
      "Easy 30-day returns if you're not completely satisfied with your purchase.",
  },
  {
    id: "hydrating-moisturizer",
    name: "Hydrating Moisturizer",
    price: 799,
    originalPrice: 1299,
    image: "/moisturizer-skincare-product.png",
    category: "skincare",
    subcategory: "moisturisers",
    gender: "beauty",
    rating: 4.8,
    reviewCount: 142,
    tags: ["Hydrating", "Non-greasy"],
    shortDescription: "Lightweight daily moisturizer for lasting hydration",
    description:
      "Keep your skin hydrated all day long with this lightweight daily moisturizer. The fast-absorbing formula delivers intense hydration without a greasy feel, making it perfect for all skin types. Enriched with hyaluronic acid and ceramides, it strengthens your skin barrier while providing the moisture your skin needs. Use morning and night for best results.",
    volume: "50ml",
    brand: "PureGlow",
    ingredients: [
      "Purified Water",
      "Glycerin",
      "Hyaluronic Acid",
      "Ceramides",
      "Shea Butter",
      "Jojoba Oil",
      "Vitamin E",
      "Niacinamide",
      "Natural Fragrance",
    ],
    benefits: [
      "Provides 24-hour hydration",
      "Strengthens skin barrier function",
      "Reduces appearance of fine lines",
      "Improves skin elasticity and firmness",
      "Creates a smooth base for makeup application",
    ],
    suitableFor: [
      "All skin types",
      "Dehydrated skin",
      "Mature skin",
      "Sensitive skin",
    ],
    howToUse: [
      "Apply to clean, dry skin",
      "Take a pea-sized amount and dot on forehead, cheeks, chin, and nose",
      "Gently massage using upward strokes until fully absorbed",
      "Use morning and evening after cleansing",
      "For best results, apply while skin is slightly damp",
    ],
    deliveryInfo:
      "Free delivery on orders above ₹999. Standard delivery in 3-5 business days.",
    returnPolicy:
      "Easy 30-day returns if you're not completely satisfied with your purchase.",
  },
  {
    id: "vitamin-c-serum",
    name: "Vitamin C Serum",
    price: 1299,
    originalPrice: 1999,
    image: "/vitamin-c-serum-product.png",
    category: "skincare",
    subcategory: "serum",
    gender: "beauty",
    rating: 4.9,
    reviewCount: 214,
    tags: ["Anti-aging", "Brightening"],
    shortDescription:
      "Powerful vitamin C serum for brighter, younger-looking skin",
    description:
      "Transform your skincare routine with our Vitamin C Serum. This potent formulation contains 20% stabilized vitamin C, hyaluronic acid, and vitamin E to brighten skin tone, reduce fine lines, and provide superior antioxidant protection. The lightweight, non-greasy formula absorbs quickly and works throughout the day to give you a radiant, youthful complexion.",
    volume: "30ml",
    brand: "PureGlow",
    ingredients: [
      "Purified Water",
      "20% L-Ascorbic Acid (Vitamin C)",
      "Hyaluronic Acid",
      "Vitamin E",
      "Ferulic Acid",
      "Glycerin",
      "Aloe Vera Extract",
      "Citrus Extract",
      "Natural Fragrance",
    ],
    benefits: [
      "Brightens dull skin and improves radiance",
      "Reduces hyperpigmentation and dark spots",
      "Stimulates collagen production for firmer skin",
      "Provides antioxidant protection against environmental damage",
      "Improves overall skin texture and tone",
    ],
    suitableFor: [
      "All skin types",
      "Mature skin",
      "Dull skin",
      "Hyperpigmented skin",
      "Sun-damaged skin",
    ],
    howToUse: [
      "Apply to clean, dry skin in the morning",
      "Place 3-4 drops onto fingertips",
      "Gently pat and press into face and neck, avoiding the eye area",
      "Allow to fully absorb before applying moisturizer and sunscreen",
      "Store in a cool, dark place to maintain potency",
    ],
    deliveryInfo:
      "Free delivery on orders above ₹999. Standard delivery in 3-5 business days.",
    returnPolicy:
      "Easy 30-day returns if you're not completely satisfied with your purchase.",
  },
  {
    id: "beard-oil",
    name: "Premium Beard Oil",
    price: 499,
    originalPrice: 799,
    image: "/beard-oil-product.png",
    category: "men-grooming",
    subcategory: "beard-essentials",
    gender: "beauty",
    rating: 4.5,
    reviewCount: 78,
    tags: ["Men's Grooming", "Nourishing"],
    shortDescription: "Nourishing beard oil for softer, healthier facial hair",
    description:
      "This premium beard oil is formulated with natural oils to nourish and condition your facial hair and the skin beneath. Regular use helps to soften coarse hair, reduce itchiness, and promote healthier beard growth. The lightweight formula absorbs quickly without leaving a greasy residue, while the subtle masculine scent keeps you feeling fresh throughout the day.",
    volume: "30ml",
    brand: "GroomElite",
    ingredients: [
      "Argan Oil",
      "Jojoba Oil",
      "Sweet Almond Oil",
      "Grapeseed Oil",
      "Vitamin E",
      "Cedarwood Essential Oil",
      "Sandalwood Essential Oil",
      "Bergamot Essential Oil",
    ],
    benefits: [
      "Softens and conditions coarse beard hair",
      "Reduces itchiness and beard dandruff",
      "Moisturizes the skin beneath the beard",
      "Promotes healthier beard growth",
      "Adds a subtle natural shine",
    ],
    suitableFor: [
      "All beard types",
      "Coarse beards",
      "New beard growth",
      "Itchy beards",
      "Dry skin under beard",
    ],
    howToUse: [
      "Apply to clean, dry beard",
      "Place 3-5 drops in palm and rub hands together",
      "Work through beard from roots to tips",
      "Use fingertips to massage into skin beneath beard",
      "Use daily for best results",
    ],
    deliveryInfo:
      "Free delivery on orders above ₹999. Standard delivery in 3-5 business days.",
    returnPolicy:
      "Easy 30-day returns if you're not completely satisfied with your purchase.",
  },
];

// Function to get product by ID
export function getProductById(id: string): Product {
  const product = products.find((p) => p.id === id);

  if (!product) {
    // Return a default product if not found
    return {
      id: "not-found",
      name: "Product Not Found",
      price: 0,
      originalPrice: 0,
      image: "/product-not-found.png",
      category: "none",
      rating: 0,
      description:
        "The product you are looking for does not exist or has been removed.",
    };
  }
  return product;
}

// Function to get related products (excluding the current one)
export function getRelatedProducts(currentId: string, limit = 4): Product[] {
  return products
    .filter((product) => product.id !== currentId)
    .sort(() => 0.5 - Math.random())
    .slice(0, limit);
}

// Function to get all products
export function getAllProducts(): Product[] {
  return products;
}

// Function to get products by category
export function getProductsByCategory(category: string): Product[] {
  return products.filter((product) => product.category === category);
}

// Function to get products by gender
export function getProductsByGender(gender: string): Product[] {
  return products.filter((product) => product.gender === gender);
}

// Function to get kids products
export function getKidsProducts(): Product[] {
  return products.filter((product) => product.gender === "kids");
}

// Function to get kids products by gender
export function getKidsByGender(kidGender: string): Product[] {
  return products.filter(
    (product) => product.gender === "kids" && product.kidGender === kidGender,
  );
}

// Beauty products for the beauty shop
export const beautyProducts = [
  {
    id: "facial-cleanser-premium",
    name: "Gentle Facial Cleanser",
    price: 599,
    originalPrice: 999,
    rating: 4.8,
    image: "/facial-cleanser-product.png",
    category: "Skincare",
    subCategory: "Cleansers",
    tags: ["Skincare", "Face Wash", "Gentle"],
    discount: 40,
    isNew: false,
    isBestSeller: true,
    reviewCount: 124,
  },
  {
    id: "moisturizer-hydrating",
    name: "Hydrating Moisturizer",
    price: 799,
    originalPrice: 1299,
    rating: 4.7,
    image: "/moisturizer-skincare-product.png",
    category: "Skincare",
    subCategory: "Moisturizers",
    tags: ["Skincare", "Hydration", "Daily Care"],
    discount: 38,
    isNew: true,
    isBestSeller: false,
    reviewCount: 86,
  },
  {
    id: "vitamin-c-brightening-serum",
    name: "Vitamin C Brightening Serum",
    price: 1299,
    originalPrice: 1999,
    rating: 4.9,
    image: "/vitamin-c-serum-product.png",
    category: "Skincare",
    subCategory: "Serums",
    tags: ["Skincare", "Brightening", "Anti-aging"],
    discount: 35,
    isNew: false,
    isBestSeller: true,
    reviewCount: 142,
  },
  {
    id: "matte-lipstick-collection",
    name: "Long-Lasting Matte Lipstick",
    price: 499,
    originalPrice: 799,
    rating: 4.6,
    image: "/matte-lipstick-product.png",
    category: "Makeup",
    subCategory: "Lipstick",
    tags: ["Makeup", "Lipstick", "Matte"],
    discount: 38,
    isNew: true,
    isBestSeller: false,
    reviewCount: 78,
  },
  {
    id: "premium-beard-oil",
    name: "Premium Beard Oil",
    price: 499,
    originalPrice: 799,
    rating: 4.7,
    image: "/beard-oil-product.png",
    category: "Men's Grooming",
    subCategory: "Beard Care",
    tags: ["Men's Grooming", "Beard Care", "Oil"],
    discount: 38,
    isNew: false,
    isBestSeller: true,
    reviewCount: 64,
  },
  {
    id: "nourishing-shampoo",
    name: "Nourishing Shampoo",
    price: 399,
    originalPrice: 699,
    rating: 4.5,
    image: "/shampoo-haircare-product.png",
    category: "Haircare",
    subCategory: "Shampoo",
    tags: ["Haircare", "Shampoo", "Nourishing"],
    discount: 43,
    isNew: false,
    isBestSeller: false,
    reviewCount: 92,
  },
  {
    id: "luxury-perfume-floral",
    name: "Luxury Floral Perfume",
    price: 1999,
    originalPrice: 2999,
    rating: 4.8,
    image: "/flash-deal-luxury-serum.png",
    category: "Fragrances",
    subCategory: "Perfumes",
    tags: ["Fragrance", "Perfume", "Floral"],
    discount: 33,
    isNew: true,
    isBestSeller: true,
    reviewCount: 56,
  },
  {
    id: "anti-aging-night-cream",
    name: "Advanced Anti-Aging Night Cream",
    price: 1499,
    originalPrice: 2499,
    rating: 4.9,
    image: "/flash-deal-cosmetic-set.png",
    category: "Skincare",
    subCategory: "Moisturizers",
    tags: ["Skincare", "Anti-aging", "Night Cream"],
    discount: 40,
    isNew: false,
    isBestSeller: true,
    reviewCount: 108,
  },
  {
    id: "volumizing-mascara",
    name: "Volumizing Mascara",
    price: 599,
    originalPrice: 899,
    rating: 4.6,
    image: "/volumizing-mascara-product.png",
    category: "Makeup",
    subCategory: "Mascara",
    tags: ["Makeup", "Mascara", "Volumizing"],
    discount: 33,
    isNew: true,
    isBestSeller: false,
    reviewCount: 72,
  },
  {
    id: "moisturizing-conditioner",
    name: "Moisturizing Conditioner",
    price: 449,
    originalPrice: 749,
    rating: 4.5,
    image: "/moisturizing-conditioner-product.png",
    category: "Haircare",
    subCategory: "Conditioner",
    tags: ["Haircare", "Conditioner", "Moisturizing"],
    discount: 40,
    isNew: false,
    isBestSeller: false,
    reviewCount: 84,
  },
  {
    id: "spf-sunscreen",
    name: "SPF 50 Sunscreen",
    price: 699,
    originalPrice: 999,
    rating: 4.7,
    image: "/spf-sunscreen-product.png",
    category: "Skincare",
    subCategory: "Sunscreen",
    tags: ["Skincare", "Sunscreen", "SPF 50"],
    discount: 30,
    isNew: true,
    isBestSeller: true,
    reviewCount: 96,
  },
  {
    id: "shimmery-lip-gloss",
    name: "Shimmery Lip Gloss",
    price: 399,
    originalPrice: 599,
    rating: 4.4,
    image: "/shimmery-lip-gloss.png",
    category: "Makeup",
    subCategory: "Lip Gloss",
    tags: ["Makeup", "Lip Gloss", "Shimmer"],
    discount: 33,
    isNew: false,
    isBestSeller: false,
    reviewCount: 68,
  },
  {
    id: "men-aftershave-balm",
    name: "Soothing Aftershave Balm",
    price: 449,
    originalPrice: 699,
    rating: 4.5,
    image: "/beard-oil-product.png",
    category: "Men's Grooming",
    subCategory: "Shaving Essentials",
    tags: ["Men's Grooming", "Aftershave", "Soothing"],
    discount: 36,
    isNew: false,
    isBestSeller: false,
    reviewCount: 58,
  },
  {
    id: "men-face-wash",
    name: "Men's Charcoal Face Wash",
    price: 399,
    originalPrice: 599,
    rating: 4.6,
    image: "/facial-cleanser-product.png",
    category: "Bath and Body",
    subCategory: "Face Wash",
    tags: ["Men's Grooming", "Face Wash", "Charcoal"],
    discount: 33,
    isNew: true,
    isBestSeller: false,
    reviewCount: 74,
  },
  {
    id: "luxury-perfume-woody",
    name: "Luxury Woody Perfume",
    price: 2499,
    originalPrice: 3499,
    rating: 4.7,
    image: "/flash-deal-luxury-serum.png",
    category: "Fragrances",
    subCategory: "Perfumes",
    tags: ["Fragrance", "Perfume", "Woody"],
    discount: 29,
    isNew: false,
    isBestSeller: true,
    reviewCount: 62,
  },
  {
    id: "foundation-medium",
    name: "Medium Coverage Foundation",
    price: 899,
    originalPrice: 1299,
    rating: 4.8,
    image: "/flash-deal-cosmetic-set.png",
    category: "Makeup",
    subCategory: "Foundation",
    tags: ["Makeup", "Foundation", "Medium Coverage"],
    discount: 31,
    isNew: true,
    isBestSeller: true,
    reviewCount: 94,
  },
  {
    id: "hair-styling-gel",
    name: "Strong Hold Styling Gel",
    price: 349,
    originalPrice: 499,
    rating: 4.3,
    image: "/shampoo-haircare-product.png",
    category: "Haircare",
    subCategory: "Hair Styling",
    tags: ["Haircare", "Styling", "Strong Hold"],
    discount: 30,
    isNew: false,
    isBestSeller: false,
    reviewCount: 48,
  },
  {
    id: "exfoliating-scrub",
    name: "Gentle Exfoliating Scrub",
    price: 549,
    originalPrice: 799,
    rating: 4.6,
    image: "/facial-cleanser-product.png",
    category: "Bath and Body",
    subCategory: "Body Scrub",
    tags: ["Skincare", "Exfoliator", "Gentle"],
    discount: 31,
    isNew: false,
    isBestSeller: false,
    reviewCount: 76,
  },
  {
    id: "eye-shadow-palette",
    name: "Neutral Eye Shadow Palette",
    price: 1299,
    originalPrice: 1799,
    rating: 4.9,
    image: "/flash-deal-cosmetic-set.png",
    category: "Makeup",
    subCategory: "Eyeliner & Kajals",
    tags: ["Makeup", "Eye Shadow", "Neutral"],
    discount: 28,
    isNew: true,
    isBestSeller: true,
    reviewCount: 112,
  },
  {
    id: "hair-oil-nourishing",
    name: "Nourishing Hair Oil",
    price: 599,
    originalPrice: 899,
    rating: 4.7,
    image: "/beard-oil-product.png",
    category: "Haircare",
    subCategory: "Hair Oil",
    tags: ["Haircare", "Hair Oil", "Nourishing"],
    discount: 33,
    isNew: false,
    isBestSeller: true,
    reviewCount: 86,
  },
  {
    id: "body-wash-refreshing",
    name: "Refreshing Body Wash",
    price: 349,
    originalPrice: 499,
    rating: 4.5,
    image: "/moisturizer-skincare-product.png",
    category: "Bath and Body",
    subCategory: "Body Wash",
    tags: ["Bath", "Body Wash", "Refreshing"],
    discount: 30,
    isNew: true,
    isBestSeller: false,
    reviewCount: 68,
  },
  {
    id: "eye-cream-firming",
    name: "Firming Eye Cream",
    price: 899,
    originalPrice: 1299,
    rating: 4.8,
    image: "/vitamin-c-serum-product.png",
    category: "Skincare",
    subCategory: "Eye Cream",
    tags: ["Skincare", "Eye Cream", "Firming"],
    discount: 31,
    isNew: false,
    isBestSeller: true,
    reviewCount: 74,
  },
  {
    id: "lip-balm-moisturizing",
    name: "Moisturizing Lip Balm",
    price: 199,
    originalPrice: 299,
    rating: 4.6,
    image: "/matte-lipstick-product.png",
    category: "Skincare",
    subCategory: "Lip Balm",
    tags: ["Skincare", "Lip Balm", "Moisturizing"],
    discount: 33,
    isNew: false,
    isBestSeller: false,
    reviewCount: 92,
  },
  {
    id: "hair-wax-matte",
    name: "Matte Finish Hair Wax",
    price: 449,
    originalPrice: 649,
    rating: 4.5,
    image: "/shampoo-haircare-product.png",
    category: "Men's Grooming",
    subCategory: "Hair Wax",
    tags: ["Men's Grooming", "Hair Wax", "Matte"],
    discount: 31,
    isNew: true,
    isBestSeller: false,
    reviewCount: 56,
  },
  {
    id: "men-deodorant-sport",
    name: "Men's Sport Deodorant",
    price: 249,
    originalPrice: 349,
    rating: 4.4,
    image: "/beard-oil-product.png",
    category: "Men's Grooming",
    subCategory: "Deodorants",
    tags: ["Men's Grooming", "Deodorant", "Sport"],
    discount: 29,
    isNew: false,
    isBestSeller: true,
    reviewCount: 78,
  },
  {
    id: "women-deodorant-floral",
    name: "Women's Floral Deodorant",
    price: 249,
    originalPrice: 349,
    rating: 4.5,
    image: "/flash-deal-luxury-serum.png",
    category: "Fragrances",
    subCategory: "Deodorants",
    tags: ["Fragrance", "Deodorant", "Floral"],
    discount: 29,
    isNew: true,
    isBestSeller: false,
    reviewCount: 62,
  },
  {
    id: "nail-polish-collection",
    name: "Nail Polish Collection Set",
    price: 699,
    originalPrice: 999,
    rating: 4.7,
    image: "/flash-deal-cosmetic-set.png",
    category: "Makeup",
    subCategory: "Nail Care",
    tags: ["Makeup", "Nail Polish", "Collection"],
    discount: 30,
    isNew: true,
    isBestSeller: true,
    reviewCount: 84,
  },
];
